//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-hudson-3037-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.04.21 at 02:48:53 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.dmtf.org/wsman/discovery")
package org.dmtf.schemas.wsman.discovery;
