//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3354 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.01.23 at 08:20:53 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://test.foo")
package foo.test;
