//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.29 at 11:33:17 PDT 
//


package org.xmlsoap.schemas.ws._2005._02.wsmancat;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.xmlsoap.schemas.ws._2005._02.wsmancat.OperationType;
import org.xmlsoap.schemas.ws._2005._02.wsmancat.OptionSetType;
import org.xmlsoap.schemas.ws._2005._02.wsmancat.SelectorSetType;

@XmlAccessorType(value = javax.xml.bind.annotation.AccessType.FIELD)
@XmlType(name = "AccessType", namespace = "http://schemas.xmlsoap.org/ws/2005/02/wsmancat")
public class AccessType {

    @XmlElement(name = "Compliance", namespace = "http://schemas.xmlsoap.org/ws/2005/02/wsmancat", type = String.class)
    protected List<String> compliance;
    @XmlElement(name = "Operation", namespace = "http://schemas.xmlsoap.org/ws/2005/02/wsmancat", type = OperationType.class)
    protected List<OperationType> operation;
    @XmlElement(name = "SelectorSet", namespace = "http://schemas.xmlsoap.org/ws/2005/02/wsmancat", type = SelectorSetType.class)
    protected List<SelectorSetType> selectorSet;
    @XmlElement(name = "OptionSet", namespace = "http://schemas.xmlsoap.org/ws/2005/02/wsmancat", type = OptionSetType.class)
    protected List<OptionSetType> optionSet;

    protected List<String> _getCompliance() {
        if (compliance == null) {
            compliance = new ArrayList<String>();
        }
        return compliance;
    }

    /**
     * Gets the value of the compliance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compliance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompliance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.lang.String}
     * 
     */
    public List<String> getCompliance() {
        return this._getCompliance();
    }

    protected List<OperationType> _getOperation() {
        if (operation == null) {
            operation = new ArrayList<OperationType>();
        }
        return operation;
    }

    /**
     * Gets the value of the operation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.xmlsoap.schemas.ws._2005._02.wsmancat.OperationType}
     * 
     */
    public List<OperationType> getOperation() {
        return this._getOperation();
    }

    protected List<SelectorSetType> _getSelectorSet() {
        if (selectorSet == null) {
            selectorSet = new ArrayList<SelectorSetType>();
        }
        return selectorSet;
    }

    /**
     * Gets the value of the selectorSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectorSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectorSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.xmlsoap.schemas.ws._2005._02.wsmancat.SelectorSetType}
     * 
     */
    public List<SelectorSetType> getSelectorSet() {
        return this._getSelectorSet();
    }

    protected List<OptionSetType> _getOptionSet() {
        if (optionSet == null) {
            optionSet = new ArrayList<OptionSetType>();
        }
        return optionSet;
    }

    /**
     * Gets the value of the optionSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the optionSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptionSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.xmlsoap.schemas.ws._2005._02.wsmancat.OptionSetType}
     * 
     */
    public List<OptionSetType> getOptionSet() {
        return this._getOptionSet();
    }

}
