//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.29 at 11:33:17 PDT 
//


package org.xmlsoap.schemas.ws._2005._02.wsmancat;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.sun.xml.bind.annotation.W3CDomHandler;
import com.sun.xml.bind.annotation.XmlAnyElement;
import org.xmlsoap.schemas.ws._2005._02.wsmancat.KeywordListType;
import org.xmlsoap.schemas.ws._2005._02.wsmancat.RelationshipListType;

@XmlAccessorType(value = javax.xml.bind.annotation.AccessType.FIELD)
@XmlType(name = "ResourceType", namespace = "http://schemas.xmlsoap.org/ws/2005/02/wsmancat")
public class ResourceType {

    @XmlElement(name = "ResourceURI", namespace = "http://schemas.xmlsoap.org/ws/2005/02/wsmancat", type = String.class)
    protected String resourceURI;
    @XmlElement(name = "Notes", namespace = "http://schemas.xmlsoap.org/ws/2005/02/wsmancat", type = String.class)
    protected String notes;
    @XmlElement(name = "Vendor", namespace = "http://schemas.xmlsoap.org/ws/2005/02/wsmancat", type = String.class)
    protected String vendor;
    @XmlElement(name = "DisplayName", namespace = "http://schemas.xmlsoap.org/ws/2005/02/wsmancat", type = String.class)
    protected String displayName;
    @XmlElement(name = "Keywords", namespace = "http://schemas.xmlsoap.org/ws/2005/02/wsmancat", type = KeywordListType.class)
    protected KeywordListType keywords;
    @XmlElement(name = "Access", namespace = "http://schemas.xmlsoap.org/ws/2005/02/wsmancat", type = org.xmlsoap.schemas.ws._2005._02.wsmancat.AccessType.class)
    protected List<org.xmlsoap.schemas.ws._2005._02.wsmancat.AccessType> access;
    @XmlElement(name = "Relationships", namespace = "http://schemas.xmlsoap.org/ws/2005/02/wsmancat", type = RelationshipListType.class)
    protected RelationshipListType relationships;
    @XmlAnyElement(lax = true, value = W3CDomHandler.class)
    protected List<Object> any;
    @XmlAttribute(name = "lang", namespace = "")
    @XmlJavaTypeAdapter(value = CollapsedStringAdapter.class)
    protected String lang;

    /**
     * Gets the value of the resourceURI property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getResourceURI() {
        return resourceURI;
    }

    /**
     * Sets the value of the resourceURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setResourceURI(String value) {
        this.resourceURI = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setVendor(String value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link org.xmlsoap.schemas.ws._2005._02.wsmancat.KeywordListType}
     */
    public KeywordListType getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.xmlsoap.schemas.ws._2005._02.wsmancat.KeywordListType}
     */
    public void setKeywords(KeywordListType value) {
        this.keywords = value;
    }

    protected List<org.xmlsoap.schemas.ws._2005._02.wsmancat.AccessType> _getAccess() {
        if (access == null) {
            access = new ArrayList<org.xmlsoap.schemas.ws._2005._02.wsmancat.AccessType>();
        }
        return access;
    }

    /**
     * Gets the value of the access property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the access property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccess().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.xmlsoap.schemas.ws._2005._02.wsmancat.AccessType}
     * 
     */
    public List<org.xmlsoap.schemas.ws._2005._02.wsmancat.AccessType> getAccess() {
        return this._getAccess();
    }

    /**
     * Gets the value of the relationships property.
     * 
     * @return
     *     possible object is
     *     {@link org.xmlsoap.schemas.ws._2005._02.wsmancat.RelationshipListType}
     */
    public RelationshipListType getRelationships() {
        return relationships;
    }

    /**
     * Sets the value of the relationships property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.xmlsoap.schemas.ws._2005._02.wsmancat.RelationshipListType}
     */
    public void setRelationships(RelationshipListType value) {
        this.relationships = value;
    }

    protected List<Object> _getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return any;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.lang.Object}
     * 
     */
    public List<Object> getAny() {
        return this._getAny();
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
