//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.29 at 11:33:17 PDT 
//


package org.xmlsoap.schemas.ws._2005._02.wsmancat;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.xmlsoap.schemas.ws._2005._02.wsmancat.SelectorType;

@XmlAccessorType(value = AccessType.FIELD)
@XmlType(name = "SelectorSetType", namespace = "http://schemas.xmlsoap.org/ws/2005/02/wsmancat")
public class SelectorSetType {

    @XmlElement(name = "Selector", namespace = "http://schemas.xmlsoap.org/ws/2005/02/wsmancat", type = SelectorType.class)
    protected List<SelectorType> selector;
    @XmlAttribute(name = "Name", namespace = "")
    @XmlJavaTypeAdapter(value = CollapsedStringAdapter.class)
    protected String name;

    protected List<SelectorType> _getSelector() {
        if (selector == null) {
            selector = new ArrayList<SelectorType>();
        }
        return selector;
    }

    /**
     * Gets the value of the selector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.xmlsoap.schemas.ws._2005._02.wsmancat.SelectorType}
     * 
     */
    public List<SelectorType> getSelector() {
        return this._getSelector();
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setName(String value) {
        this.name = value;
    }

}
