//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.29 at 11:33:17 PDT 
//


package org.xmlsoap.schemas.ws._2005._02.management;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import com.sun.xml.bind.annotation.W3CDomHandler;
import com.sun.xml.bind.annotation.XmlAnyAttribute;
import com.sun.xml.bind.annotation.XmlAnyElement;
import org.w3c.dom.Element;

@XmlAccessorType(value = AccessType.FIELD)
@XmlType(name = "EventType", namespace = "http://schemas.xmlsoap.org/ws/2005/02/management")
public class EventType {

    @XmlAnyElement(value = W3CDomHandler.class)
    protected List<Element> any;
    @XmlAttribute(name = "Action", namespace = "", required = true)
    protected String action;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    protected List<Element> _getAny() {
        if (any == null) {
            any = new ArrayList<Element>();
        }
        return any;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.w3c.dom.Element}
     * 
     */
    public List<Element> getAny() {
        return this._getAny();
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setAction(String value) {
        this.action = value;
    }

    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
