//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.29 at 11:33:17 PDT 
//


package org.xmlsoap.schemas.ws._2005._02.management;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import com.sun.xml.bind.annotation.XmlAnyAttribute;

@XmlAccessorType(value = AccessType.FIELD)
@XmlType(name = "SystemType", namespace = "http://schemas.xmlsoap.org/ws/2005/02/management")
public class SystemType {

    @XmlElement(name = "System", namespace = "http://schemas.xmlsoap.org/ws/2005/02/management", type = org.xmlsoap.schemas.ws._2005._02.management.SystemType.class)
    protected List<org.xmlsoap.schemas.ws._2005._02.management.SystemType> system;
    @XmlAttribute(name = "Name", namespace = "")
    protected String name;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    protected List<org.xmlsoap.schemas.ws._2005._02.management.SystemType> _getSystem() {
        if (system == null) {
            system = new ArrayList<org.xmlsoap.schemas.ws._2005._02.management.SystemType>();
        }
        return system;
    }

    /**
     * Gets the value of the system property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the system property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.xmlsoap.schemas.ws._2005._02.management.SystemType}
     * 
     */
    public List<org.xmlsoap.schemas.ws._2005._02.management.SystemType> getSystem() {
        return this._getSystem();
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setName(String value) {
        this.name = value;
    }

    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
