//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.24 at 09:31:40 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://wiseman.dev.java.net/server/handler/config/1/resource-handler-config.xsd")
package net.java.dev.wiseman.server.handler.config._1;
