//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.29 at 11:33:17 PDT 
//


package org.xmlsoap.schemas.ws._2004._08.eventing;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import com.sun.xml.bind.annotation.W3CDomHandler;
import com.sun.xml.bind.annotation.XmlAnyAttribute;
import com.sun.xml.bind.annotation.XmlAnyElement;
import com.sun.xml.bind.annotation.XmlMixed;

@XmlAccessorType(value = AccessType.FIELD)
@XmlType(name = "FilterType", namespace = "http://schemas.xmlsoap.org/ws/2004/08/eventing")
public class FilterType {

    @XmlMixed
    @XmlAnyElement(lax = true, value = W3CDomHandler.class)
    protected List<Object> content;
    @XmlAttribute(name = "Dialect", namespace = "")
    protected String dialect;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    protected List<Object> _getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return content;
    }

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.w3c.dom.Element}
     * {@link java.lang.String}
     * {@link java.lang.Object}
     * 
     */
    public List<Object> getContent() {
        return this._getContent();
    }

    /**
     * Gets the value of the dialect property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getDialect() {
        return dialect;
    }

    /**
     * Sets the value of the dialect property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setDialect(String value) {
        this.dialect = value;
    }

    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
