//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.09 at 04:32:30 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.dmtf.org/wbem/wsman/identity/1/wsmanidentity.xsd")
package org.dmtf.schemas.wbem.wsman.identity._1.wsmanidentity;
