//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.14 at 11:14:29 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://examples.hp.com/ws/wsman/user", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hp.examples.ws.wsman.user;
