//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.29 at 11:33:17 PDT 
//


package org.xmlsoap.schemas.ws._2004._09.transfer;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import com.sun.xml.bind.annotation.W3CDomHandler;
import com.sun.xml.bind.annotation.XmlAnyElement;

@XmlAccessorType(value = AccessType.FIELD)
@XmlType(name = "AnyXmlOptionalType", namespace = "http://schemas.xmlsoap.org/ws/2004/09/transfer")
public class AnyXmlOptionalType {

    @XmlAnyElement(lax = true, value = W3CDomHandler.class)
    protected Object any;

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link org.w3c.dom.Element}
     *     {@link java.lang.Object}
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.w3c.dom.Element}
     *     {@link java.lang.Object}
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
