//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.29 at 11:33:17 PDT 
//


package org.xmlsoap.schemas.ws._2004._09.transfer;

import javax.xml.bind.annotation.XmlRegistry;
import org.xmlsoap.schemas.ws._2004._09.transfer.AnyXmlOptionalType;
import org.xmlsoap.schemas.ws._2004._09.transfer.AnyXmlType;
import org.xmlsoap.schemas.ws._2004._09.transfer.CreateResponseType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.xmlsoap.schemas.ws._2004._09.transfer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.xmlsoap.schemas.ws._2004._09.transfer
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link org.xmlsoap.schemas.ws._2004._09.transfer.CreateResponseType}
     * 
     */
    public CreateResponseType createCreateResponseType() {
        return new CreateResponseType();
    }

    /**
     * Create an instance of {@link org.xmlsoap.schemas.ws._2004._09.transfer.AnyXmlOptionalType}
     * 
     */
    public AnyXmlOptionalType createAnyXmlOptionalType() {
        return new AnyXmlOptionalType();
    }

    /**
     * Create an instance of {@link org.xmlsoap.schemas.ws._2004._09.transfer.AnyXmlType}
     * 
     */
    public AnyXmlType createAnyXmlType() {
        return new AnyXmlType();
    }

}
