//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-322 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.03.06 at 01:53:47 PM MET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://java.net/jvm", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.java.jvm;
