//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.29 at 11:33:17 PDT 
//


package org.w3._2003._05.soap_envelope;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3._2003._05.soap_envelope.Detail;
import org.w3._2003._05.soap_envelope.Faultcode;
import org.w3._2003._05.soap_envelope.Faultreason;

@XmlAccessorType(value = AccessType.FIELD)
@XmlType(name = "Fault", namespace = "http://www.w3.org/2003/05/soap-envelope")
public class Fault {

    @XmlElement(name = "Code", namespace = "http://www.w3.org/2003/05/soap-envelope", type = Faultcode.class)
    protected Faultcode code;
    @XmlElement(name = "Reason", namespace = "http://www.w3.org/2003/05/soap-envelope", type = Faultreason.class)
    protected Faultreason reason;
    @XmlElement(name = "Node", namespace = "http://www.w3.org/2003/05/soap-envelope", type = String.class)
    protected String node;
    @XmlElement(name = "Role", namespace = "http://www.w3.org/2003/05/soap-envelope", type = String.class)
    protected String role;
    @XmlElement(name = "Detail", namespace = "http://www.w3.org/2003/05/soap-envelope", type = Detail.class)
    protected Detail detail;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link org.w3._2003._05.soap_envelope.Faultcode}
     */
    public Faultcode getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.w3._2003._05.soap_envelope.Faultcode}
     */
    public void setCode(Faultcode value) {
        this.code = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link org.w3._2003._05.soap_envelope.Faultreason}
     */
    public Faultreason getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.w3._2003._05.soap_envelope.Faultreason}
     */
    public void setReason(Faultreason value) {
        this.reason = value;
    }

    /**
     * Gets the value of the node property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getNode() {
        return node;
    }

    /**
     * Sets the value of the node property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setNode(String value) {
        this.node = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the detail property.
     * 
     * @return
     *     possible object is
     *     {@link org.w3._2003._05.soap_envelope.Detail}
     */
    public Detail getDetail() {
        return detail;
    }

    /**
     * Sets the value of the detail property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.w3._2003._05.soap_envelope.Detail}
     */
    public void setDetail(Detail value) {
        this.detail = value;
    }

}
