//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.29 at 11:33:17 PDT 
//


package org.w3._2003._05.soap_envelope;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import org.w3._2003._05.soap_envelope.Body;
import org.w3._2003._05.soap_envelope.Detail;
import org.w3._2003._05.soap_envelope.Envelope;
import org.w3._2003._05.soap_envelope.Fault;
import org.w3._2003._05.soap_envelope.Faultcode;
import org.w3._2003._05.soap_envelope.Faultreason;
import org.w3._2003._05.soap_envelope.Header;
import org.w3._2003._05.soap_envelope.NotUnderstoodType;
import org.w3._2003._05.soap_envelope.Reasontext;
import org.w3._2003._05.soap_envelope.Subcode;
import org.w3._2003._05.soap_envelope.SupportedEnvType;
import org.w3._2003._05.soap_envelope.UpgradeType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3._2003._05.soap_envelope package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Body_QNAME = new QName("http://www.w3.org/2003/05/soap-envelope", "Body");
    private final static QName _Upgrade_QNAME = new QName("http://www.w3.org/2003/05/soap-envelope", "Upgrade");
    private final static QName _Header_QNAME = new QName("http://www.w3.org/2003/05/soap-envelope", "Header");
    private final static QName _Envelope_QNAME = new QName("http://www.w3.org/2003/05/soap-envelope", "Envelope");
    private final static QName _NotUnderstood_QNAME = new QName("http://www.w3.org/2003/05/soap-envelope", "NotUnderstood");
    private final static QName _Fault_QNAME = new QName("http://www.w3.org/2003/05/soap-envelope", "Fault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3._2003._05.soap_envelope
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link org.w3._2003._05.soap_envelope.Detail}
     * 
     */
    public Detail createDetail() {
        return new Detail();
    }

    /**
     * Create an instance of {@link org.w3._2003._05.soap_envelope.Subcode}
     * 
     */
    public Subcode createSubcode() {
        return new Subcode();
    }

    /**
     * Create an instance of {@link org.w3._2003._05.soap_envelope.Fault}
     * 
     */
    public Fault createFault() {
        return new Fault();
    }

    /**
     * Create an instance of {@link org.w3._2003._05.soap_envelope.UpgradeType}
     * 
     */
    public UpgradeType createUpgradeType() {
        return new UpgradeType();
    }

    /**
     * Create an instance of {@link org.w3._2003._05.soap_envelope.SupportedEnvType}
     * 
     */
    public SupportedEnvType createSupportedEnvType() {
        return new SupportedEnvType();
    }

    /**
     * Create an instance of {@link org.w3._2003._05.soap_envelope.Envelope}
     * 
     */
    public Envelope createEnvelope() {
        return new Envelope();
    }

    /**
     * Create an instance of {@link org.w3._2003._05.soap_envelope.Header}
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link org.w3._2003._05.soap_envelope.Faultreason}
     * 
     */
    public Faultreason createFaultreason() {
        return new Faultreason();
    }

    /**
     * Create an instance of {@link org.w3._2003._05.soap_envelope.Reasontext}
     * 
     */
    public Reasontext createReasontext() {
        return new Reasontext();
    }

    /**
     * Create an instance of {@link org.w3._2003._05.soap_envelope.Body}
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link org.w3._2003._05.soap_envelope.Faultcode}
     * 
     */
    public Faultcode createFaultcode() {
        return new Faultcode();
    }

    /**
     * Create an instance of {@link org.w3._2003._05.soap_envelope.NotUnderstoodType}
     * 
     */
    public NotUnderstoodType createNotUnderstoodType() {
        return new NotUnderstoodType();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.w3._2003._05.soap_envelope.Body>}
     * 
     */
    @XmlElementDecl(name = "Body", namespace = "http://www.w3.org/2003/05/soap-envelope")
    public JAXBElement<Body> createBody(Body value) {
        return new JAXBElement<Body>(_Body_QNAME, ((Class) Body.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.w3._2003._05.soap_envelope.UpgradeType>}
     * 
     */
    @XmlElementDecl(name = "Upgrade", namespace = "http://www.w3.org/2003/05/soap-envelope")
    public JAXBElement<UpgradeType> createUpgrade(UpgradeType value) {
        return new JAXBElement<UpgradeType>(_Upgrade_QNAME, ((Class) UpgradeType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.w3._2003._05.soap_envelope.Header>}
     * 
     */
    @XmlElementDecl(name = "Header", namespace = "http://www.w3.org/2003/05/soap-envelope")
    public JAXBElement<Header> createHeader(Header value) {
        return new JAXBElement<Header>(_Header_QNAME, ((Class) Header.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.w3._2003._05.soap_envelope.Envelope>}
     * 
     */
    @XmlElementDecl(name = "Envelope", namespace = "http://www.w3.org/2003/05/soap-envelope")
    public JAXBElement<Envelope> createEnvelope(Envelope value) {
        return new JAXBElement<Envelope>(_Envelope_QNAME, ((Class) Envelope.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.w3._2003._05.soap_envelope.NotUnderstoodType>}
     * 
     */
    @XmlElementDecl(name = "NotUnderstood", namespace = "http://www.w3.org/2003/05/soap-envelope")
    public JAXBElement<NotUnderstoodType> createNotUnderstood(NotUnderstoodType value) {
        return new JAXBElement<NotUnderstoodType>(_NotUnderstood_QNAME, ((Class) NotUnderstoodType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.w3._2003._05.soap_envelope.Fault>}
     * 
     */
    @XmlElementDecl(name = "Fault", namespace = "http://www.w3.org/2003/05/soap-envelope")
    public JAXBElement<Fault> createFault(Fault value) {
        return new JAXBElement<Fault>(_Fault_QNAME, ((Class) Fault.class), null, value);
    }

}
