//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.29 at 11:33:17 PDT 
//


package org.w3._2003._05.soap_envelope;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;

@XmlAccessorType(value = AccessType.FIELD)
@XmlType(name = "subcode", namespace = "http://www.w3.org/2003/05/soap-envelope")
public class Subcode {

    @XmlElement(name = "Value", namespace = "http://www.w3.org/2003/05/soap-envelope", type = QName.class)
    protected QName value;
    @XmlElement(name = "Subcode", namespace = "http://www.w3.org/2003/05/soap-envelope", type = org.w3._2003._05.soap_envelope.Subcode.class)
    protected org.w3._2003._05.soap_envelope.Subcode subcode;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.namespace.QName}
     */
    public QName getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.namespace.QName}
     */
    public void setValue(QName value) {
        this.value = value;
    }

    /**
     * Gets the value of the subcode property.
     * 
     * @return
     *     possible object is
     *     {@link org.w3._2003._05.soap_envelope.Subcode}
     */
    public org.w3._2003._05.soap_envelope.Subcode getSubcode() {
        return subcode;
    }

    /**
     * Sets the value of the subcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.w3._2003._05.soap_envelope.Subcode}
     */
    public void setSubcode(org.w3._2003._05.soap_envelope.Subcode value) {
        this.subcode = value;
    }

}
