//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.29 at 11:33:17 PDT 
//


package org.w3._2003._05.soap_envelope;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3._2003._05.soap_envelope.SupportedEnvType;

@XmlAccessorType(value = AccessType.FIELD)
@XmlType(name = "UpgradeType", namespace = "http://www.w3.org/2003/05/soap-envelope")
public class UpgradeType {

    @XmlElement(name = "SupportedEnvelope", namespace = "http://www.w3.org/2003/05/soap-envelope", type = SupportedEnvType.class)
    protected List<SupportedEnvType> supportedEnvelope;

    protected List<SupportedEnvType> _getSupportedEnvelope() {
        if (supportedEnvelope == null) {
            supportedEnvelope = new ArrayList<SupportedEnvType>();
        }
        return supportedEnvelope;
    }

    /**
     * Gets the value of the supportedEnvelope property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportedEnvelope property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportedEnvelope().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.w3._2003._05.soap_envelope.SupportedEnvType}
     * 
     */
    public List<SupportedEnvType> getSupportedEnvelope() {
        return this._getSupportedEnvelope();
    }

}
