//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-06/22/2005 01:29 PM(ryans)-EA2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.10.27 at 11:49:42 AM PDT 
//


package org.xmlsoap.schemas.ws._2005._06.management;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * Java class for EnumerationModeType.
 *  <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EnumerationModeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EnumerateEPR"/>
 *     &lt;enumeration value="EnumerateObjectAndEPR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum(String.class)
public enum EnumerationModeType {

    @XmlEnumValue("EnumerateEPR")
    ENUMERATE_EPR("EnumerateEPR"),
    @XmlEnumValue("EnumerateObjectAndEPR")
    ENUMERATE_OBJECT_AND_EPR("EnumerateObjectAndEPR");
    public final String value;

    EnumerationModeType(String v) {
        value = v;
    }

}
