//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.29 at 11:33:17 PDT 
//


package org.xmlsoap.schemas.ws._2004._09.enumeration;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import org.xmlsoap.schemas.ws._2004._09.enumeration.Enumerate;
import org.xmlsoap.schemas.ws._2004._09.enumeration.EnumerateResponse;
import org.xmlsoap.schemas.ws._2004._09.enumeration.EnumerationContextType;
import org.xmlsoap.schemas.ws._2004._09.enumeration.EnumerationEnd;
import org.xmlsoap.schemas.ws._2004._09.enumeration.FilterType;
import org.xmlsoap.schemas.ws._2004._09.enumeration.GetStatus;
import org.xmlsoap.schemas.ws._2004._09.enumeration.GetStatusResponse;
import org.xmlsoap.schemas.ws._2004._09.enumeration.ItemListType;
import org.xmlsoap.schemas.ws._2004._09.enumeration.LanguageSpecificStringType;
import org.xmlsoap.schemas.ws._2004._09.enumeration.Pull;
import org.xmlsoap.schemas.ws._2004._09.enumeration.PullResponse;
import org.xmlsoap.schemas.ws._2004._09.enumeration.Release;
import org.xmlsoap.schemas.ws._2004._09.enumeration.Renew;
import org.xmlsoap.schemas.ws._2004._09.enumeration.RenewResponse;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.xmlsoap.schemas.ws._2004._09.enumeration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SupportedDialect_QNAME = new QName("http://schemas.xmlsoap.org/ws/2004/09/enumeration", "SupportedDialect");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.xmlsoap.schemas.ws._2004._09.enumeration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link org.xmlsoap.schemas.ws._2004._09.enumeration.LanguageSpecificStringType}
     * 
     */
    public LanguageSpecificStringType createLanguageSpecificStringType() {
        return new LanguageSpecificStringType();
    }

    /**
     * Create an instance of {@link org.xmlsoap.schemas.ws._2004._09.enumeration.EnumerationContextType}
     * 
     */
    public EnumerationContextType createEnumerationContextType() {
        return new EnumerationContextType();
    }

    /**
     * Create an instance of {@link org.xmlsoap.schemas.ws._2004._09.enumeration.GetStatus}
     * 
     */
    public GetStatus createGetStatus() {
        return new GetStatus();
    }

    /**
     * Create an instance of {@link org.xmlsoap.schemas.ws._2004._09.enumeration.GetStatusResponse}
     * 
     */
    public GetStatusResponse createGetStatusResponse() {
        return new GetStatusResponse();
    }

    /**
     * Create an instance of {@link org.xmlsoap.schemas.ws._2004._09.enumeration.Renew}
     * 
     */
    public Renew createRenew() {
        return new Renew();
    }

    /**
     * Create an instance of {@link org.xmlsoap.schemas.ws._2004._09.enumeration.FilterType}
     * 
     */
    public FilterType createFilterType() {
        return new FilterType();
    }

    /**
     * Create an instance of {@link org.xmlsoap.schemas.ws._2004._09.enumeration.Pull}
     * 
     */
    public Pull createPull() {
        return new Pull();
    }

    /**
     * Create an instance of {@link org.xmlsoap.schemas.ws._2004._09.enumeration.PullResponse}
     * 
     */
    public PullResponse createPullResponse() {
        return new PullResponse();
    }

    /**
     * Create an instance of {@link org.xmlsoap.schemas.ws._2004._09.enumeration.RenewResponse}
     * 
     */
    public RenewResponse createRenewResponse() {
        return new RenewResponse();
    }

    /**
     * Create an instance of {@link org.xmlsoap.schemas.ws._2004._09.enumeration.ItemListType}
     * 
     */
    public ItemListType createItemListType() {
        return new ItemListType();
    }

    /**
     * Create an instance of {@link org.xmlsoap.schemas.ws._2004._09.enumeration.EnumerateResponse}
     * 
     */
    public EnumerateResponse createEnumerateResponse() {
        return new EnumerateResponse();
    }

    /**
     * Create an instance of {@link org.xmlsoap.schemas.ws._2004._09.enumeration.EnumerationEnd}
     * 
     */
    public EnumerationEnd createEnumerationEnd() {
        return new EnumerationEnd();
    }

    /**
     * Create an instance of {@link org.xmlsoap.schemas.ws._2004._09.enumeration.Enumerate}
     * 
     */
    public Enumerate createEnumerate() {
        return new Enumerate();
    }

    /**
     * Create an instance of {@link org.xmlsoap.schemas.ws._2004._09.enumeration.Release}
     * 
     */
    public Release createRelease() {
        return new Release();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<java.lang.String>}
     * 
     */
    @XmlElementDecl(name = "SupportedDialect", namespace = "http://schemas.xmlsoap.org/ws/2004/09/enumeration")
    public JAXBElement<String> createSupportedDialect(String value) {
        return new JAXBElement<String>(_SupportedDialect_QNAME, ((Class) String.class), null, value);
    }

}
