//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.29 at 11:33:17 PDT 
//


package org.xmlsoap.schemas.ws._2004._09.enumeration;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import com.sun.xml.bind.annotation.XmlAnyAttribute;
import org.xmlsoap.schemas.ws._2004._09.enumeration.EnumerationContextType;

@XmlAccessorType(value = AccessType.FIELD)
@XmlType(name = "", propOrder = {
    "enumerationContext"
})
@XmlRootElement(name = "Release", namespace = "http://schemas.xmlsoap.org/ws/2004/09/enumeration")
public class Release {

    @XmlElement(name = "EnumerationContext", namespace = "http://schemas.xmlsoap.org/ws/2004/09/enumeration", type = EnumerationContextType.class)
    protected EnumerationContextType enumerationContext;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the enumerationContext property.
     * 
     * @return
     *     possible object is
     *     {@link org.xmlsoap.schemas.ws._2004._09.enumeration.EnumerationContextType}
     */
    public EnumerationContextType getEnumerationContext() {
        return enumerationContext;
    }

    /**
     * Sets the value of the enumerationContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.xmlsoap.schemas.ws._2004._09.enumeration.EnumerationContextType}
     */
    public void setEnumerationContext(EnumerationContextType value) {
        this.enumerationContext = value;
    }

    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
