//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.09 at 04:32:30 PM PDT 
//


package org.xmlsoap.schemas.ws._2005._06.wsmancat;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccessType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccessType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Compliance" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded"/>
 *         &lt;element name="Operation" type="{http://schemas.xmlsoap.org/ws/2005/06/wsmancat}OperationType" maxOccurs="unbounded"/>
 *         &lt;element name="SelectorSet" type="{http://schemas.xmlsoap.org/ws/2005/06/wsmancat}SelectorSetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OptionSet" type="{http://schemas.xmlsoap.org/ws/2005/06/wsmancat}OptionSetType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccessType", propOrder = {
    "compliance",
    "operation",
    "selectorSet",
    "optionSet"
})
public class AccessType {

    @XmlElement(name = "Compliance", namespace = "http://schemas.xmlsoap.org/ws/2005/06/wsmancat", required = true)
    protected List<String> compliance;
    @XmlElement(name = "Operation", namespace = "http://schemas.xmlsoap.org/ws/2005/06/wsmancat", required = true)
    protected List<OperationType> operation;
    @XmlElement(name = "SelectorSet", namespace = "http://schemas.xmlsoap.org/ws/2005/06/wsmancat", required = true)
    protected List<SelectorSetType> selectorSet;
    @XmlElement(name = "OptionSet", namespace = "http://schemas.xmlsoap.org/ws/2005/06/wsmancat", required = true)
    protected List<OptionSetType> optionSet;

    /**
     * Gets the value of the compliance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compliance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompliance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCompliance() {
        if (compliance == null) {
            compliance = new ArrayList<String>();
        }
        return this.compliance;
    }

    /**
     * Gets the value of the operation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OperationType }
     * 
     * 
     */
    public List<OperationType> getOperation() {
        if (operation == null) {
            operation = new ArrayList<OperationType>();
        }
        return this.operation;
    }

    /**
     * Gets the value of the selectorSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectorSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectorSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelectorSetType }
     * 
     * 
     */
    public List<SelectorSetType> getSelectorSet() {
        if (selectorSet == null) {
            selectorSet = new ArrayList<SelectorSetType>();
        }
        return this.selectorSet;
    }

    /**
     * Gets the value of the optionSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the optionSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptionSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OptionSetType }
     * 
     * 
     */
    public List<OptionSetType> getOptionSet() {
        if (optionSet == null) {
            optionSet = new ArrayList<OptionSetType>();
        }
        return this.optionSet;
    }

}
