//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-06/22/2005 01:29 PM(ryans)-EA2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.10.27 at 11:49:42 AM PDT 
//


package org.xmlsoap.schemas.ws._2005._06.wsmancat;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import org.xmlsoap.schemas.ws._2005._06.wsmancat.AccessType;
import org.xmlsoap.schemas.ws._2005._06.wsmancat.Catalog;
import org.xmlsoap.schemas.ws._2005._06.wsmancat.KeywordListType;
import org.xmlsoap.schemas.ws._2005._06.wsmancat.OperationType;
import org.xmlsoap.schemas.ws._2005._06.wsmancat.OptionSetType;
import org.xmlsoap.schemas.ws._2005._06.wsmancat.OptionType;
import org.xmlsoap.schemas.ws._2005._06.wsmancat.RelationshipListType;
import org.xmlsoap.schemas.ws._2005._06.wsmancat.RelationshipType;
import org.xmlsoap.schemas.ws._2005._06.wsmancat.ResourceType;
import org.xmlsoap.schemas.ws._2005._06.wsmancat.SchemaRefType;
import org.xmlsoap.schemas.ws._2005._06.wsmancat.SelectorSetType;
import org.xmlsoap.schemas.ws._2005._06.wsmancat.SelectorType;
import org.xmlsoap.schemas.ws._2005._06.wsmancat.SimpleRefType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.xmlsoap.schemas.ws._2005._06.wsmancat package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Resource_QNAME = new QName("http://schemas.xmlsoap.org/ws/2005/06/wsmancat", "Resource");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.xmlsoap.schemas.ws._2005._06.wsmancat
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RelationshipListType }
     * 
     */
    public RelationshipListType createRelationshipListType() {
        return new RelationshipListType();
    }

    /**
     * Create an instance of {@link ResourceType }
     * 
     */
    public ResourceType createResourceType() {
        return new ResourceType();
    }

    /**
     * Create an instance of {@link SelectorSetType }
     * 
     */
    public SelectorSetType createSelectorSetType() {
        return new SelectorSetType();
    }

    /**
     * Create an instance of {@link OperationType }
     * 
     */
    public OperationType createOperationType() {
        return new OperationType();
    }

    /**
     * Create an instance of {@link SchemaRefType }
     * 
     */
    public SchemaRefType createSchemaRefType() {
        return new SchemaRefType();
    }

    /**
     * Create an instance of {@link SimpleRefType }
     * 
     */
    public SimpleRefType createSimpleRefType() {
        return new SimpleRefType();
    }

    /**
     * Create an instance of {@link OptionSetType }
     * 
     */
    public OptionSetType createOptionSetType() {
        return new OptionSetType();
    }

    /**
     * Create an instance of {@link Catalog }
     * 
     */
    public Catalog createCatalog() {
        return new Catalog();
    }

    /**
     * Create an instance of {@link KeywordListType }
     * 
     */
    public KeywordListType createKeywordListType() {
        return new KeywordListType();
    }

    /**
     * Create an instance of {@link SelectorType }
     * 
     */
    public SelectorType createSelectorType() {
        return new SelectorType();
    }

    /**
     * Create an instance of {@link RelationshipType }
     * 
     */
    public RelationshipType createRelationshipType() {
        return new RelationshipType();
    }

    /**
     * Create an instance of {@link OptionType }
     * 
     */
    public OptionType createOptionType() {
        return new OptionType();
    }

    /**
     * Create an instance of {@link AccessType }
     * 
     */
    public AccessType createAccessType() {
        return new AccessType();
    }

    /**
     * Create an instance of {@link JAXBElement<ResourceType> }}
     * 
     */
    @XmlElementDecl(name = "Resource", namespace = "http://schemas.xmlsoap.org/ws/2005/06/wsmancat")
    public JAXBElement<ResourceType> createResource(ResourceType value) {
        return new JAXBElement<ResourceType>(_Resource_QNAME, ((Class) ResourceType.class), null, value);
    }

}
